import Head from "next/head";
import React from "react";
import dynamic from "next/dynamic";

const Remote1Content = dynamic(() => import("remote1/Content"), { ssr: true });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div
          style={{
            backgroundColor: "black",
            color: "lightgrey",
            padding: "1rem",
          }}
          onClick={() => alert("shell is interactive")}
        >
          <h1>Module Federation Example: Server Side Rendering</h1>
          <h2>This is the shell application.</h2>
        </div>

        <React.Suspense fallback={<h1>Loading....</h1>}>
          <Remote1Content />
        </React.Suspense>
      </div>
    </>
  );
}
